---
title: "Grouping Sosie based on photometric data"
author: "Ruiyang Gan"
date: "10/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
```

# Sosie Query
```{}
SELECT TOP 2000
   p.objid,p.ra,p.dec,p.u,p.g,p.r,p.i,p.z,
   p.cModelMag_u as c_u, p.cModelMag_g as c_g, cModelMag_r as c_r,
   p.cModelMag_i as c_i, p.cModelMag_z as c_z,
   p.deVAB_u, p.deVAB_r, p.deVAB_i, p.deVAB_z, 
   p.deVAB_g,
   p.expAB_u, p.expAB_g, p.expAB_r, p.expAB_i,
   p.expAB_z,
   s.specobjid, s.class, s.z as redshift
FROM PhotoObj AS p
   JOIN SpecObj AS s ON s.bestobjid = p.objid
WHERE 
   s.z BETWEEN 0 AND 10
   and s.class = "GALAXY"
```

```{r prelim, include=FALSE}
dat_small <- read.csv("Photo_pairs.csv", header = TRUE, skip = 1)
library(mclust)
```

# One dimensional classification of galaxies based on redshift
```{r fig.height = 8, fig.width = 14, echo=FALSE}
dat_small.sub = subset(dat_small, select=c("redshift"))

# Fit a 
BIC <- mclustBIC(dat_small.sub)
plot(BIC)
mod1 <- Mclust(dat_small.sub, x = BIC)
summary(mod1)
redshiftGroup <- mod1$classification
par(mfrow = c(2,3))
sapply(1:length(table(redshiftGroup)), function(d) {
	  hist(dat_small$redshift[], 
	  		 main = paste0("Histogram of galaxies' redshift within group",d),
	  		 xlab = "Red shift")
	})
```
