---
title: "Revised_small_scale"
author: "Ruiayng Gan"
date: "10/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dbscan)
```

# Prepare the data
```{r}
# Read in small scaled data
dat_small <- read.csv("../Data/Photo_pairs.csv", 
											header = TRUE, skip = 1, 
											numerals="no.loss")
redshift <- dat_small$redshift
```


# A helper function for pairs cataloging
```{r}
pairsCatalog <- function(pairs, vec){
	#' pairsCatalog 
	#'
	#' A function that takes in a list pairs and a vec consisited of galaxy IDs; returns
	#' a list which has cataloged vec 
	#' 
	#' pairs should be a list where each cell contains galaxy IDs. Each cell represents
	#' a sosie pair (or triplets). 
	#' 
	#' vec is a vector which contains ID that is supposed to be catalogued in the pairs
	
	# Instantiate the updated vector
	pairs.updated <- pairs
	cross_listed <- FALSE
	# for(pair in pairs){
	# 	# If the pair doesn't contain the objects, then just
	# 	# append the vector to updated lists
	# 	if(sum(pair %in% vec) == 0){
	# 		pairs.updated <- append(pairs.updated, list(pair))
	# 	} 
	# 	else{
	# 		# If the pair intersects with vec (contain same id), then group
	# 		# the pair and vec into a new group and append to the updated 
	# 		# pairs
	# 		cross_listed <- TRUE
	# 		pairs.updated <- append(pairs.updated, 
	# 					 								list(unique(c(pair, vec))))
	# 	}
	# }
	# if(! cross_listed) {
	# 	pairs.updated <- append(pairs.updated, list(vec))
	# }
	return(append(pairs.updated, list(vec)))
}
```

# Clustering Procedure
```{r}
# Use rolling window to obtain subset of galaxies with similar redshift
# Use window centers evenly spread out through the range of 
redshift_centers <- seq(from = min(dat_small$redshift),
												to = max(dat_small$redshift),
												length.out=11)

# Use normalized composite magnitude
cMag_bands <- c("c_g", "c_r", "c_i", "c_z")
cMag_norm <- dat_small[, cMag_bands[1:4]]/dat_small$c_u
cMag_scaled <- scale(cMag_norm, center=FALSE)

# Use a bandwidth of 0.5 to select galaxy with similar red shifts
# at each window center
h <- 0.5

# Establish a new list called sosies, which stores our
# sosie paris (or triplets)
sosies <- list()

for(c in redshift_centers) {
	# Obtain the filtered galaxies 
	indx <- (1:nrow(dat_small))[abs(redshift-c) <= h/2]
	dat_sub <- dat_small[indx,]
	# Continue if the subset has more than 1 observation
	if (length(indx) > 1) {
		print(length(indx))
		# Use DBSCAN to find pairs based on Normalized Magnitude
		rslt <- dbscan(cMag_norm[indx, ], minPts = 2, eps = .003)$cluster
		# if there is only noise, then skip; otherwise, catalog the pairs with
		# their ID
		if(length(unique(rslt)) != 1) {
			# Obtain total number of groups in clustering result
			group.level <- unique(rslt)
			for(group in group.level[-1]){
				# Obtain id for the galaxies that are classified
				# as pairs 
				groupId <- dat_sub$objid[rslt == group]
				#print(groupId)
				sosies <- pairsCatalog(sosies, groupId)
			}
		}
	}
}

# Delete duplicate pairs in lists
sosies <- unique(sosies)
```


# Check results
```{r}
# Check the clustering result
total_pairs <- length(sosies)
rslt1 <- dat_small[sosies[[sample(1:total_pairs, 1)]], ]
matplot(t(rslt1[,c("c_u","c_g","c_r","c_i","c_z")]),type='l',
				ylab = "CMag", xlab = "Colorbands",
				x = c(3543,4770,6231,7625,9134))
```


# AB ratio added
```{r}

```

